CLI
Gammanik/bash pull request #2
Opened 2020-08-13 15:09 UTC by Gammanik

Add `pwd`, `cat`, `echo`, `exit`, `wc` commands support
Pipes and quotes support with the environment substitution.

2020-08-25 16:39 UTC, yurii-litvinov requested changes
```
Gammanik-bash>$x=1
Gammanik-bash>$echo $x
1 x
```
--- неожиданно. При этом `x=11` работает ожидаемо, `echo` выводит 11

Ещё одна странность:
```
echo 123 | wc | wc
		1		1		10
```
--- судя по wc, одно слово в выводе, а должно быть три. Просто `echo 123 | wc` правильно работает. Табуляция не считается в реализации wc за разделитель?

И ещё:
```
Gammanik-bash>$x=1
Gammanik-bash>$echo "'$x'"
'null
```
Должно быть '1' (двойные кавычки "эскейпят" одинарные).

Если внешний процесс по тем или иным причинам не удалось запустить, всё падает, а надо просто ругаться и продолжать работу.

В целом, однако, всё ок, но надо поправить.

2020-08-25 16:39 UTC, yurii-litvinov commented on README.md
> +![bash](./src/main/java/docs/bash.png)
Тут внезапно диаграмма классов рогалика

2020-08-25 16:39 UTC, yurii-litvinov commented on README.md
> +![classes](./src/main/java/docs/diagram.png)
А автоматически сгенерированная диаграмма не очень информативна, на ней не отображаются взаимосвязи между классами, кроме наследования. IDEA вроде позволяет её  вручную редактировать, так что стоит её дополнить

2020-08-25 16:39 UTC, yurii-litvinov commented on src/main/java/Bash.kt
> +class Bash {
Надо комментарии. К каждому классу, интерфейсу и т.д., и каждому паблик-методу

2020-08-25 16:39 UTC, yurii-litvinov commented on src/main/java/commands/Echo.kt
> +        if(args.size != other.args.size)
Пробела перед `(` не хватает :)

2020-08-25 16:39 UTC, yurii-litvinov commented on src/main/java/commands/External.kt
> +        pb.command("bash", "-c", "$cmdString ${args.joinToString(separator = " ")}")
Это не очень работает под Windows (по крайней мере, без специальных усилий), так что эта строка привносит неоправданную некроссплатформенность. Я бы советовал запускать внешний процесс прямо через ProcessBuilder.

2020-08-25 16:39 UTC, yurii-litvinov commented on src/main/java/commands/Wc.kt
> +            line.split(" ").forEach {
В настоящем wс используется более точное понятие границы слова, и довольно специфичное. Можно ограничиться регэкспом "разделители", просто пробел не подойдёт хотя бы потому, что бывают табуляции.

2020-08-25 16:39 UTC, yurii-litvinov commented on src/main/java/util/Substitutor.kt
> +                val varName = getVarName(line.substring(i+1))
`i+1` пишется как `i + 1`, стайлгайд и всё такое. Мелочь, но должно быть на подсознательном уровне :)

2020-08-25 16:39 UTC, yurii-litvinov commented on src/test/java/CommandsIntegrationTest.kt
> +        val command = "$input\n exit" // add exit command
Тесты яростно не проходят под Windows из-за разницы в переводах строк (там `\r\n`), опять-таки, неоправданная привязка к операционной системе. В стандартной библиотеке вроде есть метод, который как раз представляет правильные переводы строк под текущую ОС.

2020-08-29 18:22 UTC, Gammanik commented on src/test/java/CommandsIntegrationTest.kt
> +        val command = "$input\n exit" // add exit command
Добавил строчку ниже. Но на Windows не тестировал. 
```kotlin
process = if (osName.contains("win"))
                ProcessBuilder("CMD", "/C", cmd).start()
            else ProcessBuilder("/bin/bash", "-c", cmd).start()
```

Хотел попробовать запустить в докер-образе или настроить, чтобы трэвис прогонял тесты на Windows, но оказалось, что это не так просто.

2020-08-29 18:22 UTC, Gammanik commented on src/main/java/commands/External.kt
> +        pb.command("bash", "-c", "$cmdString ${args.joinToString(separator = " ")}")
Добавил строчку ниже. Но на Windows не тестировал. 
```kotlin
process = if (osName.contains("win"))
                ProcessBuilder("CMD", "/C", cmd).start()
            else ProcessBuilder("/bin/bash", "-c", cmd).start()
```

Хотел попробовать запустить в докер-образе или настроить, чтобы трэвис прогонял тесты на Windows, но оказалось, что это не так просто.

2020-08-29 18:22 UTC, Gammanik commented on src/main/java/commands/Wc.kt
> +            line.split(" ").forEach {
Добавил регексп разделитель

2020-08-29 18:24 UTC, Gammanik commented on src/main/java/util/Substitutor.kt
> +                val varName = getVarName(line.substring(i+1))
Исправил

2020-08-29 18:24 UTC, Gammanik commented on src/main/java/commands/Echo.kt
> +        if(args.size != other.args.size)
Подправил

2020-08-29 18:24 UTC, Gammanik commented on src/main/java/Bash.kt
> +class Bash {
Добавил еще комментарии

2020-08-29 18:24 UTC, Gammanik commented on README.md
> +![classes](./src/main/java/docs/diagram.png)
Вставил диаграмму с взаимосвязями перед ней

2020-08-29 18:24 UTC, Gammanik commented on README.md
> +![bash](./src/main/java/docs/bash.png)
Перепутал. Сейчас исправлено

2020-08-29 18:25 UTC, Gammanik commented
Исправил ошибки с кавычками, подстановкой и `Wc`
Добавил на это тесты

2020-08-30 10:14 UTC, yurii-litvinov commented on src/main/java/commands/External.kt
> +        pb.command("bash", "-c", "$cmdString ${args.joinToString(separator = " ")}")
Я для CI под Windows обычно использую AppVeyor --- сервис типа Travis, но создававшийся изначально для Windows/.NET приложений. Сейчас и Travis как-то умеет Windows, и AppVeyor как-то умеет Linux (и далеко не только .NET), но на AppVeyor работа с Windows гораздо удобнее (например, там есть адекватная версия JDK прямо из коробки). Это можно не править, просто к сведению.

2020-08-30 10:34 UTC, yurii-litvinov requested changes
Стало существенно лучше, но кое-что надо ещё поправить. Например, улучшить диагностику ошибок пользователя: `cat .gitignore |` сейчас просто ничего не делает, а должно быть что-то, что позволит пользователю понять, что он неправ, и продолжить работу.

2020-08-30 10:34 UTC, yurii-litvinov commented on README.md
> +If com.bash.commands are piped the output of a previous command goes as an input for the next one.
Опять IDEA сделала автозамену там, где её не просили. Лучше всегда просматривать результат автозамены --- автозамена в комментариях и документации хороша (не даёт комментариям протухнуть), но часто случаются вот такие казусы.

2020-08-30 10:34 UTC, yurii-litvinov commented on src/main/java/com/bash/commands/External.kt
> + * redirecting the com.bash.commands to real bash and returns it's output
То же самое, автозамена пошла не так

2020-08-30 10:34 UTC, yurii-litvinov commented on src/test/java/com/bash/CommandsIntegrationTest.kt
> +        val input = "x=1\necho \$x"
Так всё равно переводы строк всё ломают. Из этого набора под виндой проходит ровно один тест.

2020-08-30 10:34 UTC, yurii-litvinov commented on src/main/java/com/bash/commands/External.kt
> +            else ProcessBuilder("/bin/bash", "-c", cmd).start()
Под Windows это работает (что удивительно, без тестирования-то), но не выводится stderr (и думаю, что это и на других ОС так, попробуйте `git ololo` в качестве внешней команды).

2020-08-30 13:43 UTC, Gammanik commented on README.md
> +If com.bash.commands are piped the output of a previous command goes as an input for the next one.
Поправил!

2020-08-30 13:43 UTC, Gammanik commented on src/main/java/com/bash/commands/External.kt
> + * redirecting the com.bash.commands to real bash and returns it's output
Поправил!

2020-08-30 13:44 UTC, Gammanik commented on src/test/java/com/bash/CommandsIntegrationTest.kt
> +        val input = "x=1\necho \$x"
Недоглядел. Поправил

2020-08-30 13:44 UTC, Gammanik commented on src/main/java/com/bash/commands/External.kt
> +            else ProcessBuilder("/bin/bash", "-c", cmd).start()
Поправил, теперь выводится

2020-08-30 13:45 UTC, Gammanik commented
Для случая `cat .gitignore |` добавил обработчик `handleLastPipeIsEmpty`

2020-08-30 16:14 UTC, yurii-litvinov approved these changes
handleLastPipeIsEmpty ведёт себя всё равно непонятно для пользователя:
```
Gammanik-bash>$cat .gitignore |
>
```
--- что оно от меня хочет? :) В коде-то понятно, что написано, но повторный запрос команды никак не объясняет, почему не выполнился первый, и приглашение ко вводу отличается от обычного.

И под Windows с тестами не всё так просто, wc по файлу, например, другой ответ возвращает из-за того, что в файле не те переводы строк. И cat ещё почему-то не работает в тестах.

Но ладно, все основные замечания поправлены, так что не буду Вас больше мучить, зачтена.

2020-08-30 16:30 UTC, Gammanik commented
> handleLastPipeIsEmpty ведёт себя всё равно непонятно для пользователя:
> 
> ```
> Gammanik-bash>$cat .gitignore |
> >
> ```
> 
> --- что оно от меня хочет? :) В коде-то понятно, что написано, но повторный запрос команды никак не объясняет, почему не выполнился первый, и приглашение ко вводу отличается от обычного.
> 
> И под Windows с тестами не всё так просто, wc по файлу, например, другой ответ возвращает из-за того, что в файле не те переводы строк. И cat ещё почему-то не работает в тестах.
> 
> Но ладно, все основные замечания поправлены, так что не буду Вас больше мучить, зачтена.

Спасибо!
Сделал так же, как оно работает в моем терминале)
Там тоже символ `>` и предыдущая команда сразу не выводится, а подается как инпут к введенной далее.

Например, в тесте:
```kotlin
    @Test
    fun testEmptyPipeClickEnter() {
        val input = "echo lol |$sep$sep$sep$sep cat"
        val expectedOut = ">>>>lol"
        checkCommand(input, expectedOut)
    }
```
Команда `cat` выводит аргумент из `echo`

2020-08-30 16:31 UTC, merged

2020-08-30 16:35 UTC, yurii-litvinov commented
Ну кстати да, "как в линуксе" --- хороший аргумент, убедили.