CLI 2: grep command
Gammanik/bash pull request #5
Opened 2020-08-30 17:03 UTC by Gammanik

Add `Grep` command with tests

2020-09-02 09:53 UTC, yurii-litvinov requested changes
- Довольно важной частью условия было обоснование выбора библиотеки --- почему  именно JCommander? По каким критериям сравнивали? С кем? Это надо про каждую библиотеку указывать и в архитектурной документации и в реальной жизни (и в тексте диплома, например), потому что если требования к проекту изменятся, возможно, придётся пересмотреть выбор, или кто-то найдёт какую-нибудь крутую библиотеку --- было бы хорошо видеть, что Вы её тоже рассматривали и отвергли по таким-то причинам.
- Неплохо бы тут тоже сделать так, чтобы по gradle run запускалось
- На `grep -A plugin build.gradle` падает и убивает весь шелл, надо сделать обработку ошибок (на `-A -1` тоже надо ругаться, кстати)

2020-09-02 09:53 UTC, yurii-litvinov commented on src/main/java/com/bash/commands/Grep.kt
> +        val br: BufferedReader
- В этом методе вообще как-то много сокращений идентификаторов. Лучше их не сокращать вовсе (expression вместо expr, например) --- написать идентификатор надо всего один раз, потом автодополнение. А читать приятнее.
- Тактическое соображение --- br можно было объявить внутри try и сразу присвоить ему значение, а последний return тоже затащить в try. Неинициализированная переменная, которая ещё и используется ниже по коду в `CmdRes(getMatched(p, br), "")`, меня очень пугает на уровне подсознания (хоть тут и всё ок, но это надо в код вчитываться).

2020-09-02 09:53 UTC, yurii-litvinov commented on src/test/java/com/bash/ParserTest.kt
> +            assertEquals(true, res.caseInsensitivity)
А есть же assertTrue

2020-09-05 17:13 UTC, Gammanik commented on src/main/java/com/bash/commands/Grep.kt
> +        val br: BufferedReader
Исправил и добавил обработку ошибок

2020-09-05 17:13 UTC, Gammanik commented on src/test/java/com/bash/ParserTest.kt
> +            assertEquals(true, res.caseInsensitivity)
Поправил

2020-09-05 17:21 UTC, Gammanik commented
Добавил обоснование выбора библиотеки: 
https://github.com/Gammanik/bash/blob/dev-2/src/main/java/com/bash/docs/parsing-lib.md

По `gradle run` запускается, но просто выводит бесконечный цикл :(

2020-09-05 17:21 UTC, Gammanik commented
Можно ли задание с `cd ls` сделать в своем репозитории?

2020-09-06 12:07 UTC, yurii-litvinov approved these changes
В целом всё хорошо. Зачтена

2020-09-06 12:07 UTC, yurii-litvinov commented on src/main/java/com/bash/docs/parsing-lib.md
> +Eventually, I have chosen [jcommander](http://jcommander.org/) mostly because of user-friendly documentation web-cite with [`kotlin`](http://jcommander.org/#_kotlin) section in it.
👍

2020-09-06 12:07 UTC, yurii-litvinov commented on build.gradle
> +mainClassName = 'com.bash.MainKt'
Надо ещё добавить 
```
run {
    standardInput = System.in
}
```
Чтобы как раз бесконечного цикла не было, иначе чтение с консоли будет просто пустую строку возвращать всегда.

2020-09-06 12:08 UTC, yurii-litvinov commented
> Можно ли задание с `cd ls` сделать в своем репозитории?

Не-а, там основной смысл как раз в том, что надо разобраться с чужим кодом. Но можно сделать на базе репозитория Александра Чернокоза, например. У него CLI уже почти зачтена.

2020-09-06 13:58 UTC, Gammanik commented on build.gradle
> +mainClassName = 'com.bash.MainKt'
Добавил, спасибо!

2020-09-06 14:00 UTC, merged